# Generated by Django 4.2.13 on 2024-06-14 15:12

import accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='useraccount',
            managers=[
                ('objects', accounts.managers.UserAccountManager()),
            ],
        ),
    ]
